POST http://localhost:3003/api/blogs/5d1fd44eedb1aa374383fa9b/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN3ayIsImlkIjoiNWQxZTQ5YTgwYzBkNzY1NDE5YjIzZmVhIiwiaWF0IjoxNTYyMjgyMTA4fQ.Ms6ySD276iGES51RLqeMdwF9pSxw1eGAxIoCRbkTo4k

{
  "content": "comment post"
}